image: node:16

before_script:
  - yarn install --cache-folder .yarn

# Cache node modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .yarn/

stages:
  - build
  - release
  - deploy

build:
  stage: build
  script:
    - yarn install
    - yarn test
    - yarn build
  except:
    refs:
      - /^v\d+\.\d+\.\d+.*$/

release-develop:
  stage: release
  script:
    - npx semantic-release
  artifacts:
    paths:
      - CHANGELOG.md
  only:
    refs:
      - develop

release-prod:
  stage: release
  script:
    - npx semantic-release
  artifacts:
    paths:
      - CHANGELOG.md
  only:
    refs:
      - master

pages:
  stage: deploy
  script:
    - yarn build
    - cp -r demo public
    - cp -r docs public
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - master
