os: linux
dist: xenial
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '10'
  - '12'
  - '13'
script:
  - yarn test:prod && yarn build

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: '13'
      script: skip
      on:
        branch: master
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn deploy-pages && yarn semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
